name: Push Shell Script

on:
  push:
    branches:
      - main

jobs:
  push_script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create script
      run: echo  script.sh
      

